apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: holded-devops-challenge
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: holded-devops-challenge
  releaseName: holded-devops-challenge
  chart:
    spec:
      chart: infra/helm
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  install:
    createNamespace: true
  values:
    tags:
      app: v0.0.1  # {"$imagepolicy": "flux-system:app:tag"}